name: flutter_shop
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  google_fonts: ^4.0.4
  firebase_auth: ^4.5.0
  flutter_bloc: ^8.1.2
  firebase_crashlytics: ^3.3.0
  get_it: ^7.6.0
  json_annotation: ^4.8.0
  injectable: ^2.1.1
  intl: ^0.18.0

  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
