name: flutter_shop
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  google_fonts: ^4.0.4
  firebase_auth: ^4.5.0
  flutter_bloc: ^8.1.2
  firebase_crashlytics: ^3.3.0
  get_it: ^7.6.0
  json_annotation: ^4.8.0
  injectable: ^2.1.1
  intl: ^0.18.0
  freezed_annotation: ^2.4.1
  flutter_zoom_drawer: ^3.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8

  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_pl.arb
